### ISSUE TITLE
How do you deal with recession in tech field?

### ISSUE THREAD

**Issue by MeSawSomething** [h-joo/life-in-germany#4]
Hello, I'm Miso, frontend level 0 who one day might get a career path in Germany. I found your repo on tweeter. Your motivation to create this achievement is quite inspiring for me, since I'm just a newbie in this field and thought GitHub is mainly for cool-tech-product-to-keep-newbies-away-from-them.

Anyway, I wonder

1. Do you feel 'Tech hiring freezing' in Germany as well?

2. If there's any, how do you/your surroundings (like colleagues etc) deal with it?

Thanks!
Miso

**Comment by h-joo** [comment]
Hello Miso, to answer your question

1. Yes, Germany cannot be exempted from this economic reality, thus there are many companies who're hiring slower or have done layoffs. But these I feel are mostly driven by the US companies. Yet still, you'll be able to find a job if you have at least 2-3 years of Job experience. Germany is chronically short of tech workers, and even changing the legislation quite a lot to adjust to that reality. People in reddit also claim that "Germany is short of people who're willing to work for cheap money" I also kinda feel that, but anyways it's a fact that there are many companies who still hire. 

2. I haven't lost my job, so I can't speak for myself, but even though people has lost their job, if you have experience, you'll be able to find something. People who got laid off might occasionally lower their salary expectations if they were already in a very high salary band but I don't know anyone who lost their job and was not able to find a new one.

**Comment by MeSawSomething** [comment]
Thanks for your prompt and fulfilled comment, H-joo!
Have a beautiful weekend and I will return and open another issues if there's any.

Miso
